// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlcfUvrHo9TPvC8TDY2F8rn5HCxwKCEos',
    appId: '1:625049701631:web:ab17a375e2937eaf1f90ca',
    messagingSenderId: '625049701631',
    projectId: 'worktrack-7a319',
    authDomain: 'worktrack-7a319.firebaseapp.com',
    storageBucket: 'worktrack-7a319.firebasestorage.app',
    measurementId: 'G-8MVH5W61YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP8ckGmSvsi5pJmjGSNL4xy0dDD945cUc',
    appId: '1:625049701631:android:b00936995de49c241f90ca',
    messagingSenderId: '625049701631',
    projectId: 'worktrack-7a319',
    storageBucket: 'worktrack-7a319.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpRV7lAQIoPGZpAiFpml5LJMgJPB3L5Ns',
    appId: '1:625049701631:ios:840945873165e9df1f90ca',
    messagingSenderId: '625049701631',
    projectId: 'worktrack-7a319',
    storageBucket: 'worktrack-7a319.firebasestorage.app',
    iosClientId: '625049701631-sa54lgq8scur49gjr6he3ceqmjcuckmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.superAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpRV7lAQIoPGZpAiFpml5LJMgJPB3L5Ns',
    appId: '1:625049701631:ios:840945873165e9df1f90ca',
    messagingSenderId: '625049701631',
    projectId: 'worktrack-7a319',
    storageBucket: 'worktrack-7a319.firebasestorage.app',
    iosClientId: '625049701631-sa54lgq8scur49gjr6he3ceqmjcuckmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.superAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlcfUvrHo9TPvC8TDY2F8rn5HCxwKCEos',
    appId: '1:625049701631:web:deec91244778d9a11f90ca',
    messagingSenderId: '625049701631',
    projectId: 'worktrack-7a319',
    authDomain: 'worktrack-7a319.firebaseapp.com',
    storageBucket: 'worktrack-7a319.firebasestorage.app',
    measurementId: 'G-FT4XQZT0FS',
  );
}
